name: CI/CD with Argo CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/podinfo-api
      WORKING_DIR: docs/excercise/05/pods/dotnetcore-minimal-api
    
    outputs:
      image: ${{ steps.build-image.outputs.image }}
      tag: ${{ steps.build-image.outputs.tag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
      
    - name: Restore dependencies
      working-directory: ${{ env.WORKING_DIR }}
      run: dotnet restore PodInfoApi.csproj

    - name: Build project
      working-directory: ${{ env.WORKING_DIR }}
      run: dotnet build PodInfoApi.csproj --configuration Release
      
    - name: Build Docker image
      id: build-image
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        TAG=${GITHUB_SHA::7}
        docker build -t $IMAGE:$TAG .
        echo "image=$IMAGE" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT
      
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: docker push ${{ steps.build-image.outputs.image }}:${{ steps.build-image.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      IMAGE: ${{ needs.build.outputs.image }}
      TAG: ${{ needs.build.outputs.tag }}
      WORKING_DIR: docs/excercise/05/pods/dotnetcore-minimal-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Kubernetes manifests with new image tag
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        sed -i 's|image: .*|image: '"$IMAGE:$TAG"'|' deployment-action/deployment.yaml
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ github.token }}@github.com/ryzam/devops.git
        git add deployment-action/deployment.yaml
        git commit -m "Update image to $IMAGE:$TAG"
        git push origin main

    - name: Print message
      run: echo "Deployed $IMAGE:$TAG successfully!"