name: CI/CD with Argo CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/${{secrets.DOCKER_USERNAME}}/podinfo-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Adjust the .NET version as necessary

    - name: Change to project directory
      run: |
        cd docs/excercise/05/pods/dotnetcore-minimal-api/
        ls -la
      
    - name: Restore dependencies
      run: dotnet restore docs/excercise/05/pods/dotnetcore-minimal-api/PodInfoApi.csproj

    - name: Build project
      run: dotnet build docs/excercise/05/pods/dotnetcore-minimal-api/PodInfoApi.csproj --configuration Release
      
    - name: Build Docker image
      run: |
        TAG=${GITHUB_SHA::7}  
        cd docs/excercise/05/pods/dotnetcore-minimal-api/
        docker build -t $IMAGE:$TAG .
      
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: docker push $IMAGES:$TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Update Kubernetes manifests with new image tag
      run: |
        sed -i 's|image: .*$|image: ${{ secrets.DOCKER_USERNAME }}/$IMAGE:$TAG|' deployment-action/deployment.yaml
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add deployment-action/deployment.yaml
        git commit -m "Update image to ${{ secrets.DOCKER_USERNAME }}/$IMAGE:$TAG"
        git push origin main

    - name: Print message
      run: echo "Hello, this is a simple GitHub Action! Update"